name: interactive_marker_twist_server_ci

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  humble_ci:
    name: Humble OSRF Industrial
    strategy:
      matrix:
        env:
          - {ROS_REPO: testing, ROS_DISTRO: humble}
          - {ROS_REPO: main, ROS_DISTRO: humble}
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
  jazzy_ci:
    name: Jazzy OSRF Industrial
    strategy:
      matrix:
        env:
          - {ROS_REPO: testing, ROS_DISTRO: jazzy}
          - {ROS_REPO: main, ROS_DISTRO: jazzy}
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}